# EXAM03: Data Science Group Assignment - Iteration 1

**Group name:** [Enter Group Number]

**Student names & numbers:**
* [Name 1] - [Student no.]
* [Name 2] - [Student no.]
* [Name 3] - [Student no.]

---

## 0. Setup

**Import libraries**

In [53]:
# CODE CELL: import the necessary libraries for this iteration
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

**Load dataset(s)**

In [54]:
# CODE CELL: import the necessary dataset(s) for this iteration
df_observation = pd.read_csv("./data/Dicentrarchus labrax.csv")
df_habitats = pd.read_csv("./data/habitats_cbs_2022.csv")

C:\Users\xuehu\AppData\Local\Temp\ipykernel_161636\235491660.py:2: DtypeWarning: Columns (0: Dicentrarchus labrax) have mixed types. Specify dtype option on import or set low_memory=False.
  df_observation = pd.read_csv("./data/Dicentrarchus labrax.csv")

In [55]:
df_observation.head()

,decimalLatitude,decimalLongitude,eventDate,total_observations,speciesgroup_observations,Dicentrarchus labrax
0,50.75,5.65,2010-01-01,0.0,0,0
1,50.75,5.65,2010-01-02,26.0,0,0
2,50.75,5.65,2010-01-03,3.0,0,0
3,50.75,5.65,2010-01-04,0.0,0,0
4,50.75,5.65,2010-01-05,0.0,0,0

In [56]:
df_observation.info()

<class 'pandas.DataFrame'>
RangeIndex: 12558786 entries, 0 to 12558785
Data columns (total 6 columns):
 #   Column                     Dtype
---  ------                     -----
 0   decimalLatitude            float64
 1   decimalLongitude           float64
 2   eventDate                  str
 3   total_observations         float64
 4   speciesgroup_observations  int64
 5   Dicentrarchus labrax       object
dtypes: float64(3), int64(1), object(1), str(1)
memory usage: 574.9+ MB

In [57]:
df_observation.describe()

,decimalLatitude,decimalLongitude,total_observations,speciesgroup_observations
count,1.255879e+07,1.255879e+07,1.255878e+07,1.255879e+07
mean,5.222995e+01,5.532896e+00,8.142825e+00,8.972531e-02
std,6.647267e-01,8.779710e-01,6.265301e+01,2.515470e+00
min,3.500000e+00,3.350000e+00,0.000000e+00,0.000000e+00
25%,5.170000e+01,4.900000e+00,0.000000e+00,0.000000e+00
50%,5.220000e+01,5.650000e+00,1.000000e+00,0.000000e+00
75%,5.280000e+01,6.200000e+00,6.000000e+00,0.000000e+00
max,5.350000e+01,5.340000e+01,1.000400e+05,1.011000e+03

In [ ]:
df_merged = pd.merge(
    df_observation, 
    df_habitats, 
    on=['decimalLatitude', 'decimalLongitude'], 
    how='left'
)

# df_merged["Dicentrarchus labrax"] = pd.to_numeric(df_merged["Dicentrarchus labrax"], errors="coerce")

,decimalLatitude,decimalLongitude,eventDate,total_observations,speciesgroup_observations,Dicentrarchus labrax,agricultural,built,coast,forest,other,sand/heather,water,wetland,main_habitat
12558756,3.55,53.40,2026-01-01,50.0,1011,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558757,3.65,53.40,2026-01-02,20.0,1011,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558758,3.75,53.40,2026-01-03,100.0,1011,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558759,3.50,53.30,2026-01-04,20.0,1011,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558760,3.50,53.20,2026-01-05,80.0,1011,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558761,3.50,53.10,2026-01-06,90.0,1011,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558762,3.60,53.10,2026-01-07,20.0,1011,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558763,3.70,53.10,2026-01-08,20.0,1011,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558764,3.80,53.10,2026-01-09,20.0,1011,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558765,3.50,53.00,2026-01-10,20.0,1011,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558766,3.80,53.00,2026-01-11,60.0,1011,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558767,3.50,52.90,2026-01-12,90.0,1011,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558768,3.80,52.90,2026-01-13,100.0,1011,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558769,3.50,52.80,2026-01-14,80.0,1011,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558770,3.60,52.80,2026-01-15,50.0,1011,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558771,3.70,52.80,2026-01-16,30.0,1011,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558772,3.80,52.80,2026-01-17,99999.0,1011,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558773,4.15,53.40,2026-01-18,50.0,1011,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558774,4.25,53.40,2026-01-19,50.0,1011,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558775,4.35,53.40,2026-01-20,50.0,1011,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558776,4.45,53.40,2026-01-21,99999.0,1011,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558777,4.55,53.40,2026-01-22,NaN,1011,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558778,4.45,53.30,2026-01-23,30.0,1011,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558779,4.40,53.25,2026-01-24,99999.0,1011,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558780,4.35,53.20,2026-01-25,80.0,1011,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558781,4.30,53.10,2026-01-26,10.0,1011,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558782,4.25,53.05,2026-01-27,50.0,1011,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558783,4.20,52.95,2026-01-28,20.0,1011,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558784,4.15,52.90,2026-01-29,50.0,1011,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558785,4.10,52.80,2026-01-30,100.0,1011,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
# CODE CELL: Missing values in the merged dataset
df_missing = df_merged[df_merged.isnull().any(axis=1)]
display(df_missing) 

df_clean = df_merged.dropna(subset=['agricultural'], how='all')
display(df_clean.isnull().sum().to_frame(name='missing_count'))

,decimalLatitude,decimalLongitude,eventDate,total_observations,speciesgroup_observations,Dicentrarchus labrax,agricultural,built,coast,forest,other,sand/heather,water,wetland,main_habitat
12558756,3.55,53.40,2026-01-01,50.0,1011,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558757,3.65,53.40,2026-01-02,20.0,1011,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558758,3.75,53.40,2026-01-03,100.0,1011,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558759,3.50,53.30,2026-01-04,20.0,1011,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558760,3.50,53.20,2026-01-05,80.0,1011,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558761,3.50,53.10,2026-01-06,90.0,1011,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558762,3.60,53.10,2026-01-07,20.0,1011,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558763,3.70,53.10,2026-01-08,20.0,1011,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558764,3.80,53.10,2026-01-09,20.0,1011,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558765,3.50,53.00,2026-01-10,20.0,1011,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558766,3.80,53.00,2026-01-11,60.0,1011,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558767,3.50,52.90,2026-01-12,90.0,1011,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558768,3.80,52.90,2026-01-13,100.0,1011,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558769,3.50,52.80,2026-01-14,80.0,1011,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558770,3.60,52.80,2026-01-15,50.0,1011,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558771,3.70,52.80,2026-01-16,30.0,1011,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558772,3.80,52.80,2026-01-17,99999.0,1011,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558773,4.15,53.40,2026-01-18,50.0,1011,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558774,4.25,53.40,2026-01-19,50.0,1011,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558775,4.35,53.40,2026-01-20,50.0,1011,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558776,4.45,53.40,2026-01-21,99999.0,1011,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558777,4.55,53.40,2026-01-22,NaN,1011,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558778,4.45,53.30,2026-01-23,30.0,1011,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558779,4.40,53.25,2026-01-24,99999.0,1011,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558780,4.35,53.20,2026-01-25,80.0,1011,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558781,4.30,53.10,2026-01-26,10.0,1011,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558782,4.25,53.05,2026-01-27,50.0,1011,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558783,4.20,52.95,2026-01-28,20.0,1011,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558784,4.15,52.90,2026-01-29,50.0,1011,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12558785,4.10,52.80,2026-01-30,100.0,1011,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

                           missing_count
decimalLatitude                        0
decimalLongitude                       0
eventDate                              0
total_observations                     0
speciesgroup_observations              0
Dicentrarchus labrax                   0
agricultural                           0
built                                  0
coast                                  0
forest                                 0
other                                  0
sand/heather                           0
water                                  0
wetland                                0
main_habitat                           0

---

## 1. Business Understanding
*Rubric: LO 6.4D (Reflection on Process)*

**Situation description**

*Describe the Nebula Brokerage pricing problem. Why is their current "gut feeling" approach a risk?.*

**Business objective(s)**

*Justify why a data-driven baseline is needed*

**Data mining goal(s)**

*Explain what type of modeling task this is and why.*

**Success criteria**

*Determine success criteria for this iteration (the benchmark)*

---

## 2. Data Understanding
*Rubric: LO 7.3Q (Visuals) & LO 6.4C (Process)*

**Data exploration**

*Include summary statistics and descriptions of data types below. Describe your findings.*

In [59]:
# CODE CELL: Show basic statistics and information

**Visualizations and patterns**

*Discover patterns in the data by creating visualizations. Create at least a histogram of Galactic_Credits. Describe your observations.*

In [60]:
# CODE CELL: Generate visualizations (e.g., scatter plots, histograms)

**Data insights and data quality**
* **Insights:** What are the key trends? What does the distribution look like? What does that mean? 
* **Quality issues:** Document missing values, duplicates, outliers, etc.

---

## 3. Data Preparation
*Rubric: LO 6.4C (Data Science Steps)*

**Cleaning and preprocessing**
*Describe and justify steps taken (e.g., imputation, handling outliers, fixing other errors).*

In [61]:
# CODE CELL: Data cleaning and preprocessing steps

**Adjusting dataset (optional)**
*If you adjusted the dataset for modeling in additional ways, describe that here*

In [62]:
# OPTIONAL CODE CELL: Additional preprocessing steps

---

## 4. Modeling
*Rubric: LO 6.4C (Data Science Steps)*

**Model setup**
*Describe and justify the creation of your simple benchmark model to predict Galactic_Credits*

In [63]:
# CODE CELL: Model training and setup code

**Testing and performance**
*Describe how you tested the model and interpret the metrics. Make sure to present the metrics in a clear overview.*

In [64]:
# CODE CELL: Model evaluation code

---

## 5. Evaluation
*Rubric: LO 6.4C (Results vs. Objectives)*

**Assessment against succes criteria** 
*What is the difference between the metrics? What does this mean? Did you meet the goals set in the Business Understanding?*

**Key findings and limitations**
*What did you learn? What are the limitations of this current model?*

---

## 6 Personal Contribution
*Rubric: LO 7.3P (Equal Contribution)*

| Student name | Contribution | Personal lessons learned |
| :--- | :--- | :--- |
| Student name 1 | *Contribution description* | *Personal lessons learned this iteration* |
| Student name 2 | *Contribution description* | *Personal lessons learned this iteration* |
| Student name 3 | *Contribution description* | *Personal lessons learned this iteration* |